### ISSUE TITLE
HardwareObjects submodule

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcubeqt#100]
Hi all,
A new repository for MXCuBE 3 has been created ; the idea for the new version is to have a
repository on its own, to facilitate the work with a git workflow model (feature branches, master
branch, hotfix branches etc.).
This has an impact on MXCuBE repository, since we don't want to 'fork' or maintain a copy of
Hardware Objects in two different repositories.
So the proposed solution is to make HardwareObjects a submodule of another git repository
devoted to Hardware Objects, thart will be shared both by MXCuBE and MXCuBE 3.
Is it ok for everybody if we do like this ?

**Comment by IvarsKarpics** [comment]
From my side this looks fine. 
Should we also move all hardware objects from HardwareRepository to this submodule?
Also a cleanup would not be bad (deleting not used hwobj, using site specific directories with hardware objects)

**Comment by mguijarr** [comment]
MXCuBE still depends on what is called 'Bliss Framework' (even if the Bliss Framework project itself
is dead), that's why HardwareRepository is a submodule at the moment. And it comes with its own
(supposedly) general-purpose Hardware Objects, hence the HardwareObjects subdirectory in HardwareRepository.
I don't think we can move all hardware objects to the new submodule, because the new submodule is only for MXCuBE hardware objects.
However, we may decide to simply integrate the old 'Bliss Framework' project within MXCuBE code,
without having sub-modules anymore...
Depends if Bliss Framework project is used independently of MXCuBE, maybe we can just ask at the next MXCuBE meeting.

**Comment by IvarsKarpics** [comment]
Good, then lets keep HardwareRepository (and its HardwareObjects) untouched. 
Should we remove the HardwareObjects dir from mxcube? And now start to work in new submodule? About BlissFramework I am not sure. Maybe we should create two new repositories (as submodules) for guis. Like mxcubeWebGui and mxcubeQt4Gui. 
Well, these are quite radical changes and for sure it is better to discuss these structure question during the next meeting.

**Comment by mguijarr** [comment]
I just did the change, so now the master branch of mxcube has a submodule for Hardware Objects.
