### ISSUE TITLE
Road to 2.2

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcubeqt#101]
This is a reminder for doing the work towards 2.2 version:
- to merge 2.1 branch into master
- create 2.2 from master
  I think we can say that 2.2 would become the official stable branch for Qt 4 MXCuBE 2.
  Of course development will continue on master...
  There is going to be a 2.2 branch for Hardware Objects repository too, probably.

**Comment by IvarsKarpics** [comment]
Hi all,

First of all thanks to everybody who was present in the meeting. There were lots of useful ideas and discussions. 
Regarding the roadmap. I think it was Antonio who talked about git workflows and how we should collaborate and I like the idea of not using branches but tags and feature branches.
What if we now merge 2.1 in the master and test it on the beamlines? If it is fine we put 2.1. tag.
From my side master is tested on p13, p14 and there will not be many "bazookas" commits in close future. I will continue with feature branches as you do in web.

Ivars

**Comment by IvarsKarpics** [comment]
Some ideas that could be implemented during the 2.1. merge in master.
- New directory "motors" to store all available motors
- Remove last Qt remains from HardwareObjects (like ShapeHistory in queue_entry) to be fully compatible with Qt4/web
- Split AbstractMulticollect.do_collect in several functions and delegate tasks to queue(take_snapshots, store_in_lims)
- add new hwobj advanced_queue_entry and import it in queue_entry. We keep queue_entry with basic tasks and those who are interested can extend advanced_queue_entry.
- discuss GenericDiffractometer (I will finish it soon)
- finally put a tag

**Comment by JieNanMAXIV** [comment]
In the 2.1 branch, I have moved the login logic from the ProposalBrick2 to ISPyBClient2 HO (PR accepted already). I have also updated the ProposalBrick2 recently. But since the ISPyBClient2 is not updated in the master branch, so I only have it in my repo and haven’t made the PR.

When you do the 2.1 merge, I can make a PR to the mxcube repo (for the ProposalBrick2). What do you think?

**Comment by IvarsKarpics** [comment]
Well, I assume that the merge will not be a single click so we will mostly do it manually. So we will take the differences from 2.1. and merge them in master. If we will not miss something then no PR will be necessary. Lets see how it goes.

**Comment by IvarsKarpics** [comment]
Hi all!

After some intensive days of rebasing, a new branch 2.2. is born!
I would welcome everybody to slowly move to 2.2., because all development/bugfix/etc should go there.
