### ISSUE TITLE
Ldap login / ISPyB login in ProposalBrick2 to be moved in Hardware Object

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcubeqt#102]
While playing with MXCuBE 3, we noticed some code in ProposalBrick2 is doing a Ldap login
then ISPyB login. 
This code should be moved to the ISPyBClient2 Hardware Object since it doesn't really belong
to the graphical part of MXCuBE.

**Comment by IvarsKarpics** [comment]
Do you mean moving ldap login to ISPyBClient2?
Not sure if it is necessary. Why we do not keep them separate? In our case we are not using ldap at all.

**Comment by mguijarr** [comment]
I am talking about this code in **ProposalBrick2**:

``` python
def _do_login(...):
     if not impersonate:
            login_name=self.dbConnection.translate(proposal_code,'ldap')+str(proposal_number)
            logging.getLogger().debug('ProposalBrick: querying LDAP...')
            ok, msg=self.ldapConnection.login(login_name,proposal_password)
            if not ok:
                msg="%s." % msg.capitalize()
                self.refuseLogin(None,msg)
                return

            logging.getLogger().debug("ProposalBrick: password for %s-%s validated" % (proposal_code,proposal_number))

    # Get proposal and sessions
    logging.getLogger().debug('ProposalBrick: querying ISPyB database...')
    prop=self.dbConnection.getProposal(proposal_code,proposal_number)
```

IMO the ldap part should be moved to the ISPyBClient2 hardware object - `getProposal` could be both doing ldap + getting proposal from ISPyB.
If ldap is not defined in dbconnection.xml, then it could skip the ldap part (would it be compatible with you then ? Are you using ProposalBrick2 brick ?)

**Comment by IvarsKarpics** [comment]
Ok, fine with me to move ldap to hwobj and if it is not present in xml then do not use it.
To be clear. How you authenticate user in web version? Do you authenticate user via ispyb?

**Comment by JieNanMAXIV** [comment]
The final authentication will still be done in LDAP as it is now. We will only move the ldap authentication, ldapConnection.login(login_name,proposal_password), to the ISPyBClient2 HO.  Something like,

If this.ldapConnection is not NULL:
    ldapConnection.login (name, psd)
else:
    ispyb login (name, psd)

So instead of calling the server first for authentication, then another for returning the proposal obj, it will be done in one call.

**Comment by mguijarr** [comment]
It's like Jie said.

We are reusing the exact same hardware objects - however for this authentication thing I found it
weird that non-graphical code was put in _ProposalBrick2.py_, it should have been moved to
Hardware Objects part long ago... (there are probably dozens of mistakes like this in MXCuBE...).
As the code is written at the moment it's a problem for MXCuBE 3 since it would require the same
logic as _ProposalBrick2_ to be coded in the server. Which is ok in some cases, but for this one I think we can clean it and let the server be a "dummy" connection to Hardware Objects with no
real logic.

Jie: do you have time to take care of this issue? Can it be assigned to you? 

How can we do it ? I propose:
- to make a commit in `2.1` branch of HardwareObjects
- to make a commit in `2.1` branch of MXCuBE, to change _ProposalBrick2.py_
- to make another commit in `2.1` branch of MXCuBE which would make a submodule update for HardwareObjects
- to cherry-pick the first two commits in master versions of the repositories
- to make a final commit in `mxcube/master` to update the submodule version for the master branch

**Comment by IvarsKarpics** [comment]
Maybe last two actions are not necessary now? You can do fixes in 2.1. and later merge all changes in master.

**Comment by JieNanMAXIV** [comment]
OK. I have taken it. Another way is to create a new HO, ISPyBClient3 and push it to the 2.1 branch of HardwareObjects. When we have a working ProposalBrick3, we can push it together with the ISPyBClient3 to the master branch. What do you think?

**Comment by IvarsKarpics** [comment]
Well, always we can create new files, but if it is about such a small change and rest of the code stays the same, then I don see a point of creating a new hwobj.

**Comment by mguijarr** [comment]
Agree with Ivars :) No need for another file.
Thanks for taking it Jie !

**Comment by IvarsKarpics** [comment]
I cherry-picked this commit from master and together with some bug fixes updated branch 2.2.
Could you all try branch 2.2? What do we do with master branch?

**Comment by mguijarr** [comment]
I am in favour of force-pushing 2.2 to master (to make master == 2.2), so we can continue development in master, like we said before, and have 2.2 as new stable branch.
I don't think we can make a normal push since 2.2 has been re-based on 2.1 (which is good, but it changed git history).

**Comment by IvarsKarpics** [comment]
I fully agree. Could you please do that? I am not so sure how to do that...

**Comment by pkeller** [comment]
Hi everyone, I don't have the time to look into this in detail right now, but one thing that I am concerned about is the ability to run MXCuBE in dummy mode (i.e. without any connection to a beamline or ISPyB, and without having to connect to a login service). In the past, this ability disappeared from MXCuBE, and Markus had to do some work to restore it. Dummy mode will be essential for me when I start working with MXCuBE later this year, and I will be very grateful for any efforts to keep it functional when making changes in this area. Thanks.

**Comment by IvarsKarpics** [comment]
Hi Peter,

There are no problems to run mxcube without ispyb or other login services (like LDAP). If you clone the project from git then it comes with mockup configuration that uses ISPyBClient2Mockup and MulticollectMockup. I always run mockup version on my office pc and a deploy version (real configuratin) on beamlines.

**Comment by IvarsKarpics** [comment]
This one is implemented now in hwobj. I will close this. If there is any problem then we can reopen the issue.
