### ISSUE TITLE
about queue_item.py

### ISSUE THREAD

**Issue by JieNanMAXIV** [mxcube/mxcubeqt#107]
In the queue_item.py, [line354](https://github.com/mxcube/mxcube/blob/master/Bricks/queue_item.py#L354), should it be 
queue_model_objects.XRFSpectrum: XRFSpectrumQueueItem, 
instead? Since in the queue_model_objects_v1 HO, the class is XRFSpectrum.

**Comment by IvarsKarpics** [comment]
old saga with xrf spectrum :)
yes, It should be XRFSpectrum. There was lots of discussions about this and probably with branching some XRFScan syntax is still left. 
I assume i did not fixed. because already some time I am working just with qt4 version.

**Comment by IvarsKarpics** [comment]
I will close this
