### ISSUE TITLE
Next join MXCuBE & ISPyB meeting at Hamburg, 27-29.06.2016

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/mxcubeqt#110]
Dear all,

Next join MXCuBE & ISPyB meeting will be in Hamburg and organized by EMBL Hamburg unit.
It will start at lunchtime 27th of June and finish on 29th of June (also around lunchtime).
Please start to think about possible presentations. 
Registration page and a draft program will follow soon.

Kind regards,
Ivars Karpics

**Comment by mguijarr** [comment]
Hi Ivars,

It would be good if we could have time for a kind of "code camp" for MXCuBE 3,
the idea would be to have it opened for everyone who would like to get informed
on how the development goes and if people want to participate...

Maybe the best would be to do it after the ISPyB/MXCuBE plenary meetings ?

Like on Wednesday afternoon/Thursday morning... If it's possible ?

**Comment by IvarsKarpics** [comment]
Hi Matias,

Sure, this is a good suggestion. I was thinking about something similar.
In fact we could expand this to several topics staring from hardware level till gui. Also some small git tutorial would not be bad. Of course we would not be able to cover everything, but at least give some introduction.
For sure we can have Wednesday afternoon for such a code camp, but about Thursday morning is difficult to say how much people would be still there. In the registration webpage I will ask to add some checkbox for this workshop and then lets see how much people are interested in this.

**Comment by pkeller** [comment]
I would be interested, but I need to know whether this will go ahead or not before arranging my travel. I would probably stay an extra day: taking the late flight back on Wednesday would make the journey incredibly complicated for me.

**Comment by IvarsKarpics** [comment]
Please use the link below to register to the next joint MXCuBE/ISPyB meeting:
https://embl.ungerboeck.com/prod/emc00/register.aspx?OrgCode=10&EvtID=5465&AppCode=REG&CC=116060625148

**Comment by mguijarr** [comment]
Thanks a lot Ivars !

**Comment by pkeller** [comment]
OK, I'll be there for the workshop too, although may have to leave a little early (flight back at 17:55). Ivars, you might like to get the ending year of the meeting corrected before anyone tries to import the ics file into their calendar ;-)

**Comment by IvarsKarpics** [comment]
Hi @pkeller ,

Thanks!. I already send a bug report to HR :)
Regarding the workshop, lets see how many people will apply. Anyway even if there are 2 people I think its good to learn and understand how other people are coding.

**Comment by IvarsKarpics** [comment]
Thank you all for participating in the meeting! We had a productive meeting.
I will add some highlights to the mxcube webpage.

See you next time at ESRF!
Ivars

**Comment by mguijarr** [comment]
:+1:

**Comment by jordiandreu** [comment]
Thank you Ivars for these productive days! To you and to anyone who have made this possible!

Jordi

Enviat des del meu iPhone

El 30 juny 2016, a les 8:31, Ivars Karpics notifications@github.com va escriure:
