### ISSUE TITLE
Developers workshop during the next MXCuBE meeting

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/mxcubeqt#111]
Hi all,

The idea of developers workshop is to get to know each other better, practice co-development and improve mxcube. Workshop will start at 2pm on (29.06) and end around lunchtime next day (30.06). Possible agenda could be:

29.06.2016
**Session 1. Working with git (14:00 - 16:00)**
- Personalized repository, synchronization with origin/master
- Working with local repository
- **Preparing PR**. Accepting/declining PR
- Don't be afraid of issues!!! Talk, talk, talk.
- Branches

**Session 2. Setting up mxcube web and Qt4 (16:30 - 18:00)**
- Getting code from git
- Dependencies
- Starting mxcube

30.06.2016
**Session 3. Hardware objects (hwobjs) and hardware repository (9:00 - 10:30)**
- configuring hwobj with xml
- object/equipment/procedure, main methods. Hwobj with multiple hwobj
- example: integrating diffractometer in mxcube 

**Session 4. Basic GUI development (11:00 -13:00)**
- creating a new Brick in Qt4 version. Defining GUI layout
- GUI development in web version 

If this program is to simple and everybody knows these things then we can directly work on the code. Then the main issues to be solved are:
- Branch rebase. Goal is to have a unified master and 2.2. as a stable version
- AbstractClasses

For the workshop we could use ubuntu 14.04. I would recommend to set up a clean ubuntu on a virtual machine.
Feel free to drop any idea or comment.
Cheers,

Ivars

**Comment by IvarsKarpics** [comment]
Some issues, questions...
1. Sardana motor. Is there a common one?
2. Where is the limit of beamline control system? How much we implement in MXCuBE hardware objects and how much in beamline control system?
3. Disable controls during the data collection or other movements (sample changer, etc).
4. How to handle diffractometer phases? GenericDiffractometer.
5. Demostrate TogetherJS.
6. Centring math.
7. A list of xmls for gui bricks, features.
8. Regular emails.

to be updated...

**Comment by IvarsKarpics** [comment]
Minutes:

Git workflow:
1. Branching issue. Feature based releases? Code reviewing and merging.
2. How newcomers enter co-development. **2.2**. or master (latest stable).
3. PEP guidelines is **must** before submitting code to git via PR.
4. Prepare release as branch with announced features (for example 2.3 with new queue_entry)
5. List of deprecated methods, features, hwobj's.
6. Add deprecation warning.

**Comment by meguiraun** [comment]
for the latest steps for installing the web version see ~~https://github.com/mxcube/mxcube3/issues/180.~~

I updated the wiki: https://github.com/mxcube/mxcube3/wiki/How-to:-Installation

**Comment by IvarsKarpics** [comment]
I will add more documentation about HardwareObjects and git guidlines

**Comment by vrey01** [comment]
Concerning SardanaMotor.  There were actually two versions Jan and mine.  They are very similar. After looking at them with Jan we decided to keep Jan's as the one in the repository

**Comment by meguiraun** [comment]
I updated the installations instructions for mxcube3 (aka mxcube-web). See [here](https://github.com/mxcube/mxcube3/wiki/How-to:-Installation). Ubuntu 16 and 14.

Do not hesitate opening any issue if you have any problem.
