### ISSUE TITLE
Possible to collect dataset in simulation mode?

### ISSUE THREAD

**Issue by jlmuir** [mxcube/mxcubeqt#122]
I started MXCuBE following the [How to install and run Qt version](https://github.com/mxcube/mxcube/blob/master/docs/source/installation_instructions_qt4.rst) instructions, but when I run it, the Collection Method GUI component is disabled.  Below is a screenshot.  Is this normal?  Is there a way to get a simulated setup that will let me collect a dataset?

![collection-disabled](https://cloud.githubusercontent.com/assets/959381/17526454/f3183cea-5e2c-11e6-9290-cb624bad86b7.png)

**Comment by IvarsKarpics** [comment]
Hi @jlmuir ,

Yes it is normal. In simulation mode also connection to ISPyB is simulated. You have to just click on Login button to "login" in ISPyB. Of course there are no actual connection to any ISPyB instance. After login you will be able to run collections.

**Comment by jlmuir** [comment]
OK, that worked! Thanks!
