### ISSUE TITLE
Use templates for the file names

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/mxcubeqt#127]
Add possibility to use templates for the file names.

Possible templates:
- %n : name of the container (dewar, puck, etc)
- %c : container number
- %u : username
- %p : sample position
- %s : sample name

Example: /data/%u_%c-%p_%s -> /data/myUserName_1-1_sampleName

**Comment by IvarsKarpics** [comment]
Here is a PR: #128

**Comment by mguijarr** [comment]
Wow!!! That's efficiency!!!

**Comment by IvarsKarpics** [comment]
I liked the idea and I did know where to hit (write few lines of code) :)
