### ISSUE TITLE
Wrong or unassociated author of Git commits

### ISSUE THREAD

**Issue by jlmuir** [mxcube/mxcubeqt#133]
(I'm filing this here, but it's actually an issue that applies to all the projects under the mxcube organization.)

There are a number of commits with Git author information that is incorrect.  This makes it hard to easily tell who made a change.

A secondary issue is that a number of commits have Git author information that is actually correct but that GitHub is not able to associate with a GitHub user because the email address used for the commit has not been added to the user's GitHub profile.  The downside here is that it makes it more difficult to obtain useful statistics about a project.  It's difficult to do so by hand because I would need to figure out all the email addresses or names that map to a single user.  It's difficult to do so via GitHub's tools (e.g. Graphs > Contributors) because the tools usually only work for GitHub users.  For example, the Graphs > Contributors tool only considers commits that are associated with a GitHub user.

To see examples of these, browse the commits on GitHub for a project in the mxcube organization (e.g. mxcube > Code > commits).  GitHub does not recognize the email address as being associated with a GitHub user for any commit that has a gray GitHub logo as the author's avatar.

For example, here's a commit by bliss administrator to the mxcube repo (I don't know who bliss administrator is):

![mxcube-unknown-bliss-admin](https://cloud.githubusercontent.com/assets/959381/17983808/14055d80-6ad4-11e6-9f55-0f7adde858ed.png)

And here's a commit by Mikel Eguiraun to the HardwareObjects repo (It's easy to tell the author is Mikel, but GitHub wasn't able to associate the commit with the correct GitHub user):

![mxcube-unknown-mikel-eguiraun](https://cloud.githubusercontent.com/assets/959381/17984262/fb593d7c-6ad5-11e6-9f88-68039d6ae5ff.png)

I started emailing a few people about this, but then I realized that's not a practical approach, so I'm filing this issue instead.  I think two things could be done by all contributors to address this:
1. Ensure the Git email addresses you use (i.e. `git config user.email`) have been added to your GitHub profile.  See "[Why are my contributions not showing up on my profile?](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile#you-havent-added-your-local-git-commit-email-to-your-profile)"
2. Ensure the Git `user.email` option is set correctly for any patches you send or commits you make.

**Comment by mguijarr** [comment]
bliss administrator comes from a generic user account we use at ESRF... BLISS is the name of our beamline control group. So when commits are made from the beamlines the author is often 'bliss administrator'. I am sorry about that ; I can probably change the email in the different hosts for git starting from now.

For your statistics: you can assume bliss administrator == ESRF (either Antonia, Marcus or me).

**Comment by jlmuir** [comment]
On 08/26, Matias Guijarro wrote:

> bliss administrator comes from a generic user account we use at
> ESRF... BLISS is the name of our beamline control group. So when
> commits are made from the beamlines the author is often 'bliss
> administrator'.

Ah, I see; thanks for letting me know.

> I am sorry about that ; I can probably change the email in the
> different hosts for git starting from now.

No worries; yes, that would be great if you could!  Thanks!

> For your statistics: you can assume bliss administrator == ESRF
> (either Antonia, Marcus or me).

OK, good to know.  Thanks much!
