### ISSUE TITLE
Move icons to BlissFramework/Icons

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/mxcubeqt#155]
Hi,

Would it be ok to move those two Alba icons to BlissFramework/Icons? I did not notice this icons directory in the latest PR. Its better to keep all icons in one place.

**Comment by vrey01** [comment]
I see,

I would rather remove those icons from the project. They do not correspond to the application, they are only use by the GUI file to place the 
ALBA logo on the top right corner.

**Comment by IvarsKarpics** [comment]
Done with #156
