### ISSUE TITLE
Failed to run mxcube in master branch from fresh checkout

### ISSUE THREAD

**Issue by jordiandreu** [mxcube/mxcubeqt#177]
I just downloaded latest version of mxcube and checkout the master branch. I cannot run the example mxcube gui provided because it hangs during initialization:

```
git clone git@github.com:mxcube/mxcube.git
cd mxcube/
git submodule init
git submodule update
bin/mxcube
```

The current commit is:
```
commit 3ace337c62d5a8bd14d6f9b318df0ef36e3ce546
Author: IvarsKarpics <ivars.karpics@gmail.com>
Date:   Tue May 30 14:31:47 2017 +0200

    2017.05.30. Xml config for resolution mockup
```
and linked to the hashes:
```
 2fea198f5989b1ccfa39712bc5c8c89d905a5258 BlissFramework (2fea198)
 74d682cd3497d319ae213cf1187ef27351518128 HardwareObjects (74d682c)
 ee79aa8b3fc3b52b83f3f1271a32ae2ad57fe4ee HardwareRepository (remotes/origin/bugfixes2-4-gee79aa8)
```

If one makes a checkout of the master branch for each submodule, the application can be properly started.

Is this the expected result?
Shall commit to mxcube while linking to more recent submodule's commits?

**Comment by IvarsKarpics** [comment]
Hi @jordiandreu ,

Thanks for the bug report. I will make a PR with submodule update to avoid this.

**Comment by IvarsKarpics** [comment]
Fixed
