### ISSUE TITLE
Characterization: How to select 2-image collections with 90 degree angle increment

### ISSUE THREAD

**Issue by jordiandreu** [mxcube/mxcubeqt#225]
Hi all,

We are implementing the EDNA characterization process and we are testing this feature. When we select the desired number of images for the characterization to collect, if more than one image is requested (for instance, 2 images) they are taken as a data collection entry of 2 images. i.e. the angle between images is just the one correponfing to the integration time selected, instead of a fixed angle increment ofr 90 dgrees, for example. Then, we got an error frem the EDNA plugin process:

```
[Warning]: EDPluginLabelitIndexingv1_1 execution error :
[Warning]: /mnt/hpcsoftware/bl13/phenix-1.12-2829/build/bin/labelit.screen log file:
InputFileError: Input error: Indexing unlikely to succeed with abutting images
```

Do you use characterization processes with more than one image? How can you select the angle increment between images in a characterization?

many thanks

**Comment by IvarsKarpics** [comment]
Hi @jordiandreu ,

Yes, characterization is done not just for one image, but also for 2 and 4. In the Qt4 version see:
https://github.com/mxcube/mxcube/blob/228525e68b22ac90c199729d4be15a82f5d35bf3/BlissFramework/Bricks/widgets/Qt4_create_char_widget.py#L306-L308

**Comment by jordiandreu** [comment]
Thanks for the hint!
