### ISSUE TITLE
"Unable to add channel" Error messages

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcubeqt#229]
The changes to CommandContainer lines 153-149 (commit 59f725e), cause a series of error messages when running in mock mode. AI am not sure enough of the motivation to propose a fix, but 'something ought to be done':

2018-05-14 13:55:10,264 |user_level_log|ERROR  | Unable to add channel CoaxCamScaleX
Traceback (most recent call last):
  File "/MXCuBE/mxcube/HardwareRepository/HardwareObjects/GenericDiffractometer.py", line 252, in init
    self.used_channels_list = eval(self.getProperty("used_channels"))
TypeError: eval() arg 1 must be a string or code object
2018-05-14 13:55:10,264 |user_level_log|ERROR  | Unable to add channel CoaxCamScaleY
Traceback (most recent call last):
  File "/MXCuBE/mxcube/HardwareRepository/HardwareObjects/GenericDiffractometer.py", line 252, in init
    self.used_channels_list = eval(self.getProperty("used_channels"))
TypeError: eval() arg 1 must be a string or code object

etc.

The error shown in each case comes from GenericDiffractometer line 252:
        # Channels -----------------------------------------------------------
        try:
           self.used_channels_list = eval(self.getProperty("used_channels"))
        except:
           pass # used the default value
which seems unfortunate. The error being reported is not what caused the missing channel, it is suposedly acceptable (being inside a try: except:) and the a single error occurrence is reported seven times.

Three points, in order of increasing desirability:

-1 Could the log message in CommandContainer be reduced from 'exception' to 'warning' (or at most 'error'), so as not to be so dominant?

-2 Is this level of warning/error appropriate, when it also appears in mock mode?

-3 Surely it is wrong to have GenericDiffractometer load what sounds like non-generic channels like CurrentPhase or CoaxCamScaleY, and even more so to raise user error messages when these channels are missing?

**Comment by IvarsKarpics** [comment]
Hi @rhfogh ,

I presume eval breaks with argument None. So a quick fix would be to add default value for the getProperty method, for example: 
`self.used_channels_list = eval(self.getProperty("used_channels", "[]"))`
I agree about the error handling and will have a look at this.
