### ISSUE TITLE
mxcube for the ESS

### ISSUE THREAD

**Issue by mattclarke** [mxcube/mxcubeqt#235]
Hi.

My name is Matt Clarke and I work for the ESS in experiment control and data acquisition.
I would like to learn more about mxcube as one of our beamlines (NMX) have said they will want to use mxcube in the future.

Is there anyone at MAXIV available to meet up for a chat?

I am I right in assuming that all the facilities using mxcube are running Tango?

Thanks,

Matt

**Comment by marcus-oscarsson** [comment]
Hi Matt !

Sure we are very happy to discuss how you could use MXCuBE3 for your experiments. MXCuBE3 is built on the same control layer as MXCuBE2, which we are now planning to redesign (still in the discussion and planning phase). 

The MXCuBE2 control layer is independent of control system, and it already supports SPEC, Sardana, EPICS, Tango, Tine and BLISS. I believe that basically all institutes are in fact using Tango, in one way or another (along side with one of the other control systems)

We can maybe even schedule a demo session if you are interested in that ?

Kind regards,
Marcus

**Comment by meguiraun** [comment]
Hej Matt,

Glad you are considering mxcube for ESS! LNLS (Brazil) are using mxcube with EPICS.

As Marcus pointed out, a remote demo migth be useful so you can see the remote operation. But you can also come to MAX IV and visit Biomax, yes, I am the MAX IV guy.

Mikel

**Comment by mattclarke** [comment]
Hi Marcus and Mikel.

Thank you for your responses.

A demo session would be great. Visiting Biomax would be very useful too.

And thanks for the info about EPICS; that sounds very promising.

Cheers,

Matt

**Comment by mattclarke** [comment]
Hi again.

I have looked at my calendar and was wondering if you would be free either in the last week of June or the first week of July for a remote demo?

Thanks,

Matt

**Comment by marcus-oscarsson** [comment]
Sure I think we can arrange something, although it would be difficult to do a remote demo with 
beam those dates. But we can arrange something during a machine maintenance day. I have to 
get back to you with dates for testing with beam (if necessary). 

You can also reach me at my ESRF email if you like oscarsso@esrf.fr

Cheers !
Marcus
