### ISSUE TITLE
Specification of HWobj and config search paths

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcubeqt#247]
My latest PR has removed various hardwired and duplicate sertting of HWobj and HWrepository paths.

I would propose:

- Setting site-specific directories using the environment variables and defining more than one directory to look in (as specified in e.g. Qt4_startGUI)

- making directory structure and file names identical for main HWobj and config, mock HWobj, and site specific HWobj. 

- Setting multidirectory lookup paths.

- Having the same names for config files in the various trees (i.e. NOT collect-mockup.xml, but mockup/collect.xml)

That would allow you to 

- e.g. switch from production to mock mode simply by prepending the mockup directory in the HWRserver location string

-  add a few site-specific HWobj on top of a moajority of standard ones, by prepending a sparsely populated local HWobj directory in front of the main HWobj directory,  

- switch between environments (for off-line testing) by changing a few environment variables instead of editing e.g. beamline-setup.xml

**Comment by IvarsKarpics** [comment]
Is this all still active? Maybe @rhfogh  can submit individual issues to mxcube and HardwareRepository?

**Comment by rhfogh** [comment]
This was discussed, and essentially refused, at the face-to-face meeting. I am closing it.
