### ISSUE TITLE
Qt4SlitsBrick broken outside EMBL

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcubeqt#255]
After the latest PRs, Qt4_SlitsBrick.initiate_spinboxes calls functions  self.slitbox_hwobj.get_step_sizes and self.slitbox_hwobj.get_gap_limits that are only defined for the EMBLSlitBox

The former function can be commented out (the result is not used), but the latter would need a little more thought. Could someone take a look?

**Comment by IvarsKarpics** [comment]
Hi @rhfogh ,

I do not see these two methods in the Brick. Do you have the latest version?

**Comment by rhfogh** [comment]
You are  right, I am behind, Things are moving too fast for me.

Sorry, Rasmus
