### ISSUE TITLE
Error in Qt4_TaskToolBoxBrick.py

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcubeqt#256]
I get an error Bricks/Qt4_TaskToolBoxBrick.py", line 111, in run
    self.task_tool_box_widget.adjust_width(self.width())
AttributeError: 'TaskToolBoxWidget' object has no attribute 'adjust_width'

That is AFTER doing git fetch and rebasing ;-)

Indeed there seems to be no adjust_width function in either the mxcube code or in QFrame.

Did I get it right this time?

**Comment by IvarsKarpics** [comment]
Thanks for pointing this out. see: https://github.com/mxcube/mxcube/pull/257

**Comment by rhfogh** [comment]
Looks good. Thanks.
