### ISSUE TITLE
Motor names and roles

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcubeqt#273]
The code in practice uses hardwired ESRF motor names internally (kappa_phi, sampx, ...). Whether this is the best set of names is beside the point (I prefer the ALBA names myself), but it would be useful to make this fact explicit in the documentation, and to name all the motor config files according to the role name. 'Centx' and 'Omegaz' may be better names than 'sampx' and 'phiz', but it would be easier on everybody if you knew that the relevant config files were always called 'sampx.xml' and 'phiz.xml'.

**Comment by beteva** [comment]
Agree with @rhfogh, we should have some naming convention. For me, though, what should be fixed are the roles and not the motor or the file names. Moreover, this should be done in the GenericDiffractometer.
