### ISSUE TITLE
Cleaning up the repository

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/mxcubeqt#279]
I would suggest to clean up the repository to the following structure:
+ qt_gui
   + bricks
   + widgets
   + ui_files
   + qt3_archive
   + utils
+ bin
+ doc
+ example

All Qt3 files will be moved to qt3_archive and Qt4 prefix will be removed.

**Comment by rhfogh** [comment]
Sounds reasonable - and getting widgets to the top level would be a useful move. 
Where would the current 'Icons' go? 
What would be in 'ui_files'? 
Woudl qt3_archive be for obsolete (qt3) code?

**Comment by IvarsKarpics** [comment]
* Icons -> icons
* ui_files are for storing qt designer *ui files.
* yes qt3_archive is for old qt3 code. Maybe it should have a better name: deprecated_qt3, old_qt3

**Comment by IvarsKarpics** [comment]
As we have a HardwareRepository submodule maybe then it is better to keep CapitalizedWords for directory names: Bricks, Widgets, UiFiles, Icons, Utils?

**Comment by IvarsKarpics** [comment]
Will be split in several issues
