### ISSUE TITLE
Importing from PyQt

### ISSUE THREAD

**Issue by jordiandreu** [mxcube/mxcubeqt#298]
I found some situations in which the PyQt object are directly imported from an specific PyQt version instead of using the wrapper module QtImport.py. I think we shall use this wrapper to keep the transition from different versions smooth.

(@rhfogh I found some in /BlissFramework/Bricks/widgets/Qt4_create_gphl_workflow_widget.py, for instance)

Shall this be included as part of the coding guidelines?

**Comment by IvarsKarpics** [comment]
Hi @jordiandreu ,

Thanks for pointing this out. Yes, those import from PyQt4 should be replaced with QtImport.

**Comment by IvarsKarpics** [comment]
I close this issue, because the new repository structure is based on absolute imports and to import Qt classed QtImport is used.

**Comment by marcus-oscarsson** [comment]
Great :), thanks !
