### ISSUE TITLE
mxcube 2.3.0 branch

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcubeqt#301]
I think we need a 2.3.0 branch that matches the HardwareRepository 2.3.0 branch, in case people need to do some bug fixing or similar.

The branch rhfogh/2.3.0 would do the trick, but I do not know how to copy it across to here, and probably do not have the access rights. If someone coudl do it for me it might be useful.

Happy Crhistmas, Rasmus

**Comment by IvarsKarpics** [comment]
Hi @rhfogh , could we postpone this to next year? There are still some parts missing (licence, clean up some imports and etc) and it would not be good to release a half finished version.

**Comment by rhfogh** [comment]
I was thinking of having a branch that matched the HardwareRepository  2.3.0 branch as it was just after the face-to-face meeting (and as it is now, it has not been modified since that AFAIK). The 3.0.0 branch is another matter - of course that has to wait till we have finished refactoring.

**Comment by marcus-oscarsson** [comment]
That was one of the reasons for why we created 2.3.0 branch so that does make sense :)

**Comment by rhfogh** [comment]
Looks like this is now getting superseded
