### ISSUE TITLE
Default wavelength selection

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcubeqt#311]
When running a new workflow instance, after changing a sample, what should you select as the default wavelength? The current wavelength? A configured default? The question si what the user would expect and find lest confusing/irritating.

How about detector distances, while we are at it - what should be the default there?

**Comment by marcus-oscarsson** [comment]
Its mostly a matter of what the most common use case is, we have found that users more often wants use the last entered values, which sometimes also causes some confusion. We clearly indicate when the values entered differ from the current hardware values.

The defaults when the application start is always the hardware value

We used to have logic that re-setted this in different ways for instance when the sample changed but it only made some users more confused an annoyed.

There might of course be some cases when its better to use another schema, but this is in general what we found the users have appreciated the most.

**Comment by rhfogh** [comment]
Question has been answered. Thanks @marcus-oscarsson
