### ISSUE TITLE
Discussion about Abstract Classes

### ISSUE THREAD

**Issue by beteva** [mxcube/mxcubeqt#349]
In the line of refurbishing/improving the HardwareObject and especially the Abstract classes, these are our consideration and suggestions:
1. Only one way of defining compulsory methods in the abstract classes.
Now both the ABC module or raising NotImplementedError are used. We suggest that we only use the abc module (https://docs.python.org/3/library/abc.html). It is exactly what we need - abstract base classes. It can be used both with methods and properties. For more details, have a look in the python doc. In order to be consistent, we propose the following:

> from abc import ABC
> class MyClass(ABC):
>   @abstractmethod
>   def my_method(self):

2. Properties  vs methods.
We can use both. We do not have a strong opinion but we would like to have state and value and not any property name as position, diameter or anything else. We should not forget that the HardwareObjects are not anything that is going to be executed on a command line, but
rather an abstraction layer between the GUI and the control system In this sense it will be much easier to know that no matter what king of object you will address, you can use a method (or a property) named value, instead of thinking if it is a motor (position), an aperture (diameter) or any other meaningful but also specific name for a given equipment.

3. Snake case - just a reminder

4. Remove some old/redundant abstract classes
Remove AbstractBase.py and AbstractMultiCollect.py files
Rename AbstractAttenuatiors to AbstractTransmission

5. Clear, remove and maybe rename some of the methods, which are an
inheritance of the early days of the HardwareRepository
We need to go throughout all the methods like connectNotify, isReady, update_value, value_changed. The list is not complete.

6. State handling. Last but not least
 Now there are certain number of states and different ways to define them (named tuple, enum, list).What we suggest is:
Make a finite number of states, the same for all the abstract classes which need states. We propose IntEnum with @unique decorator (good for both python 2.7 and 3). This will also ease the way of defining a colour code to be used by both WEB and QT. Here is how it can be implemented

> import enum
> @enum.unique
> class States(enum.IntEnum):
>     """
>     Enumeration of states
>     """
>     UNKNOWN = 0      # grey
>     READY = 1            # green
>     BUSY = 2              # yellow
>     FAULT = 3             # red
>     ALARM = 4           # orange
>     ON = 5                   # green
>     OFF = 6                 # white
>     DISABLED = 7      # pink
>     AUTOMATIC = 8   # dark green

MOVING can be associated with BUSY, OPEN and IN with READY, CLOSED and OUT with OFF. Something to be decided as well is if there should be a separate, but with the same values class for each object (like DiffractometerState, MotorState ...) or we define one to be used by all.

**Comment by rhfogh** [comment]
@beteva 
I highly approve

**Comment by rhfogh** [comment]
There is one snag here.
I really like the ABC module (after a quick look), but abc.ABC is python-3 only; you need to use abc.ABCMeta to have things work in 2.7. Also the recommended syntax for abstract properties are different in the two cases (though the 2.7 way still works in 3.7, as legacy, according to the documentation).
As long as we do not abandon Python-2.7 we might have to accept using ABCMeta.

**Comment by marcus-oscarsson** [comment]
Yes you are right, we have said that we will stay Python 2.7 compatible so using the ABCMeta would probably be the best option. I think its worth to re raise the question about the Python 2.7 comparability since it would make the implementation process easier if we could focus exclusively on Python3.

**Comment by rhfogh** [comment]
@marcus-oscarsson Indeed it would

**Comment by IvarsKarpics** [comment]
Can we close this issue? We discussed these questions during the developers meeting and they are included in the milestones.

**Comment by beteva** [comment]
Discussed during the developers meeting. Now  included in the milestones.
