### ISSUE TITLE
Convert filenames from CamelCase to snake_case (gui directory)

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/mxcubeqt#410]

**Comment by rhfogh** [comment]
@IvarsKarpics 
Hmmm. Bricks are camelCase, widgets are snake_case, utils are half-and-half. This is not going to be clean or quick.

I would favour taking a decision in principle for all of MXCiuBE on which naming style we want to (eventually) end on.
Specifically what to do about files that have the same name as the (main) class within them, and more generally what style of name we want for .py files. Once we agree we can move partially,fast, or slowly as makes more sense. But 1) I worry that taking decisions one directory at a time among a few people will not lead to consistency; 2) in the absence of a shared decision uou can ;point to there will be few arguments to use against anyone who just prefers his own style.

Is there a way of getting a quick round of input, at least, if we do not want to hold the entire process up? Or do we already have agreement, in your opinion, based on having opted for PEP8?

**Comment by beteva** [comment]
You are right @rhfogh, we should either follow the PEP8 rules, as we've committed to it, or make private MXCuBE rule and stick to it. Whatever it is,  it has to be for all the files and directories of the project. Once this done, we can decide the pace of the change (slow or fast).

**Comment by IvarsKarpics** [comment]
Currently, as @rhfogh  pointed out, there is a mixture and mess with filenames, constant names and etc. Somehow this needs to be clarified or/and changed. If we are saying that we follow PEP8 then we should follow it and for example also the  HardwareReposiory should be renamed, for example to hwr.
I do not see any problem in changing filenames and imports, basically it is one day task. MXCuBE project is about 15 years old and things do change, and all what we did lately is a major improvement. So why not to continue.
Maybe lets discuss this in a web meeting.

**Comment by rhfogh** [comment]
A web meeting is probably a good idea.

I'd be happy enough to go to PEP8, if we agree on that. Failing that we should agree on our own set of rules, possibly one or two different ones for different directories, so at least it is clear.

One call for creativity: PEP8 wants short, lower-case, *underscore_free* file names. Can we realistically do that? If not, which rule do we break? If yes, what is the neatest way to distinguish? Can we do it by directory, so everything in the bricks directory, widget directory ec. is assumed to be a brick/widget by default?

**Comment by jordiandreu** [comment]
Regarding the PEP8, I think we are mixing to concepts: package and module

> Any Python file is a module, its name being the file's base name without the .py extension. A package is a collection of Python modules: while a module is a single Python file, a package is a directory of Python modules containing an additional __init__.py file, to distinguish a package from a directory that just happens to contain a bunch of Python scripts. Packages can be nested to any depth, provided that the corresponding directories contain their own __init__.py file.

and what PEP8 says about naming convention is:

> Package and Module Names
Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.

So, I understand filenames can use underscores if it improves readability. Then, I would be in favour to this proposed restructure of the repository as well as to continue with the snake case convention for filenames.

Also relatedto the filenames with brick or widget suffixes, I think is also a good idea to the suffixes to get shorter names cause:
* They should all be contained into a folder with this suffix name. Then when used in any other module using absolute imports it will be easy to track if it is a widget or brick.
* The file could eventually contain other classes or objects different from the corresponding widget or brick classes.
