### ISSUE TITLE
Convert filenames from CamelCase to snake_case (bricks directory)

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/mxcubeqt#411]
Maybe remove prefix Bricks.
For example:
* ApertureBrick.py -> aperture.py
* BeamstopDistanceBrick.py -> beamstop_distance.py

**Comment by beteva** [comment]
@IvarsKarpics, Is there a reason you want to change this?  I find it handy to see if these are Bricks (even if they are in a separate directory, but can you guarantee that all the files are bricks only). I would also make that all the file names correspond to the Brick class name.

**Comment by IvarsKarpics** [comment]
Yep, you are totally right. This was not a good idea... I am closing the issue

**Comment by beteva** [comment]
In fact my comment does not follow the PEP8 convention, which might be wrong. We have been following PEP8 for names, we should agree whether it concerns file and directory names.
