### ISSUE TITLE
Create setup.py 

### ISSUE THREAD

**Issue by jordiandreu** [mxcube/mxcubeqt#413]
In line with the decisions taken for the HardwareRepository project about the _setup.py_ file, I think it would be also interesting to create a _setup.py_ file for the mxcube/mxcube project (the qt front-end version) with the aim to facilitate the deployment of the application. What do you think about it?

**Comment by rhfogh** [comment]
Sounds like a good idea - but I am not volunteering to do it.

**Comment by jordiandreu** [comment]
@rhfogh I can propose a first draft, but I would like to know if it is of interest for everyone or if there is any objection :)

**Comment by IvarsKarpics** [comment]
I am fine with creating a setup.py and @jordiandreu  please go ahead and create the first version. However we should agree on module name, structure and in general what is the scope of the module. Should one be able at some point do something like:

```
from mxcubehwr import hwr
from mxcubeqt import app as qt_app

hwr.init(PATH_TO_CONFIG)
qt_app.start(PATH_TO_CONFIG)
```


 PR #409 is the first step towards it.

**Comment by jordiandreu** [comment]
I have already proposed a draft version for the setup.py. Nevertheless, I tried to make the minimum number of changes with this proposal however, the usage of the setup.py would provide better ways to deploy and configure the application that maybe is time to face: usage of pkg_resources, avoid environment variables for configuration, and many other thinks to discuss that would probably be also linked with the changes in the hardware repository.

Cheers
