### ISSUE TITLE
QtGraphicsManager, QtGraphicsLib and InstanceServer depend on QtImport module from mxcube

### ISSUE THREAD

**Issue by jordiandreu** [mxcube/mxcubeqt#416]
Hi all,

In order to split the project in three different python packages, we need to solve the dependency of _QtGraphicsManager_, _QtGraphicsLib_ and _InstanceServer_ belonging to the **HardwareRepository** since they depend on the _QtImport_ module, which is part of the **mxcube** repository.

One option would be moving the _QtImport_ module to the HardwareRepository as part of the qt support while keeping the hierarchy between the **mxcube** and **HardwareRepository** packages. What do you think about this? any other idea or suggestion?

Cheers

**Comment by IvarsKarpics** [comment]
I am fine with moving QtImport to utils/qt_import.py of HardwareRepository

**Comment by marcus-oscarsson** [comment]
Fine for me too, see https://github.com/mxcube/HardwareRepository/pull/607#issuecomment-749165987

**Comment by IvarsKarpics** [comment]
Solved with https://github.com/mxcube/mxcubecore/pull/611
