### ISSUE TITLE
Shortcuts tied to two different actions

### ISSUE THREAD

**Issue by MartinSavko** [mxcube/mxcubeqt#419]
Hi,

"Ctrl+1" and "Ctrl+2" and some other shortcuts are defined in multiple places: HutchMenuBrick, CameraBrick and GraphicsToolsBrick.  

We run into particular problem with "Ctrl+2": in HutchMenuBrick it triggers saving of the position, while in CameraBrick it triggers the single view alignment. This lead to unintended shift in sample position and a loss of quality of alignment.

The simplest solution might be to redefine shortcuts in one of the bricks. I would go for changing it in CameraBrick as most users that use those shortcuts seem to be expecting the actions from HutchMenuBrick rather then those from CameraBrick.

Martin

**Comment by IvarsKarpics** [comment]
Hi Martin,

Thank you for the big report. I agree with you and lets keep the shortcuts just in the CameraBrick. 
I will fix this and open a PR asap.

Cheers,
Ivars

**Comment by IvarsKarpics** [comment]
Solved with #422
