### ISSUE TITLE
What happened to bin and gui

### ISSUE THREAD

**Issue by JohnDobbins** [mxcube/mxcubeqt#424]
Sorry, the issue here is I am at sea. I am trying to get started with MxCube2.  I installed code this past Feb. 15. At that time there were bin and gui directories which are referenced in this how to install and run Qt version document. 

https://github.com/mxcube/mxcube/blob/master/docs/source/installation_instructions_qt4.rst

I am trying to recreate an MxCube installation from scratch and I see that bin/ and gui/ don't appear in the master though they are in v2.4.0.

Obviously I am missing something.  Can you help? Thanks.

**Comment by IvarsKarpics** [comment]
Dear @JohnDobbins 

Currently mxcubecore (previously known as HardwareRepoisitory) and mxcube qt frontend are in structural refactoring which should be finished soon. Both of them will be available as pythong packages. To achieve this a new directory structure was introduced and gui directory got renamed to mxcubeqt and bin directory was moved to the scripts.
Previously HardwareRepository was part of mxcube as git submodule. Now it is handled as a separate python module and should not be under mxcubeqt directory. Python should just able to import the mxcubecore package and the easiest way to achieve this is to use environment variables. For example 

```
pwd
/home/mxuser

git clone https://github.com/mxcube/mxcubecore.git mxcubecore
git clone https://github.com/mxcube/mxcube mxcubeqt

export PYTHONPATH=/home/mxuser/mxcubeqt:/home/mxuser/mxcubecore
export MXCUBE_CORE_CONFIG_PATH=/home/mxuser/mxcubecore/mxcubecore/configuration/mockup/qt:/home/mxuser/mxcubecore/mxcubecore/configuration/mockup/
export MXCUBE_GUI_CONFIG_PATH=/home/mxuser/mxcubeqt/mxcubeqt/example_config.yml

#python3 -m mxcubeqt --mockupMode
python /home/mxuser/mxcubeqt/mxcubeqt $1
```

I will update README.md with instructions on how to run mxubeqt.

**Comment by JohnDobbins** [comment]
Thanks!

________________________________

**Comment by IvarsKarpics** [comment]
Documentation was updated in PR #422
