### ISSUE TITLE
Give names or numbers to lines in Helical scan

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcubeqt#56]
Now it looks like "Lines/Line/Line/...."

**Comment by IvarsKarpics** [comment]
What could be the suggestion? 
Maybe simple Line 1, Line 2 etc.
or more sophisticated: give numbers for centring positions and then Line could be:
Line 1: from point x to point y

**Comment by mguijarr** [comment]
For this feature, I prefer option 2: something more sophisticated.

However, I think we should make a bigger change: to remove helical line selection from the Helical task editor, to move it instead in a new "Shapes" brick that we would put below the sample video
brick.
Then, we could also remove the new grid button from the sample video toolbar, and have the grid
feature available in this new Shapes brick ; for any kind of shapes, user will always use the same
brick. It will also remove the need for a "diffractometer" property in the video brick.

**Comment by IvarsKarpics** [comment]
Solved in the centring_point branch and merged in to the master branch.
Lines are displayed like: Line (points 1, 2)
