### ISSUE TITLE
Unrolling inverse beam into pieces may freeze mxcube for minutes

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcubeqt#57]
Is it necessary to unroll?

**Comment by IvarsKarpics** [comment]
I found that freezing occurs in
self.tool_box.currentItem().update_selection()
in task_toolbox_widget.py (somewhere around line 200)
Not sure how to speed up this. What is the actual need of this? Maybe something more simple could work?

**Comment by IvarsKarpics** [comment]
Now the unrolling (in Qt4 version) is not done, but executed in the queue level.
