### ISSUE TITLE
Collect Queue -> Confirm Collection takes long time to unroll with ten thousands images

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcubeqt#60]

**Comment by IvarsKarpics** [comment]
Problem is in the current implementation. MXCuBe checks if each file exists and this for large data collections may take a lot of time. In principle it would be enough to check first and last image (current implementation in qt4 gui).

**Comment by hnaalas** [comment]
Dear Ivars

Sorry for stupid questions: what is the new strategy when say 10 images out of 10 thousands have been collected? What will happen?

Cheers, leo

> On 26 Apr 2016, at 08:49, Ivars Karpics notifications@github.com wrote:
> 
> Problem is in the current implementation. MXCuBe checks if each file exists and this for large data collections may take a lot of time. In principle it would be enough to check first and last image (current implementation in qt4 gui).
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub

## 

## Leonard Chavas

Synchrotron SOLEIL
Proxima-I
L'Orme des Merisiers
Saint-Aubin - BP 48
91192 Gif-sur-Yvette Cedex

## France

Phone:  +33 169 359 746
Mobile: +33 644 321 614

## E-mail: leonard.chavas@synchrotron-soleil.fr

**Comment by IvarsKarpics** [comment]
Hi,

It is a warning. If users press continue then the existing files will be overwritten. Maybe the fists and last image is not the best approach. Checking first 20 images would be enough.
