### ISSUE TITLE
Refresh Sample changer window

### ISSUE THREAD

**Issue by babubm14** [mxcube/mxcubeqt#64]
How do we refresh the sample changer window history when we inserted the new basket?

**Comment by mguijarr** [comment]
Collections on basket 1 (for example) are done, then users change basket 1 to another one at
the same position in sample changer ; even after scanning new basket 1, DC tree remains
unchanged. The question is "how do we refresh/reset the tree ?".

**Comment by IvarsKarpics** [comment]
It is done with status update timer (1 sec.) which calls _doUpdateInfo.
I am not sure if this issue is still active.

**Comment by babubm14** [comment]
Thanks, Ivars for attending this issue. - Babu
