### ISSUE TITLE
Data collection and snapshots when no centred position saved.

### ISSUE THREAD

**Issue by beteva** [mxcube/mxcubeqt#68]
When you decide to collect at the position you are, but do not want to centre (by deliberately removing centre sample from the queue), if there was previously saved position, the crystal snapshots are taken at the current position, but the data collection id done at the last saved position. Should have possibility to either save current position, without centring, or if removing centre sample from the queue to save automatically the current position as the last centred position.

**Comment by IvarsKarpics** [comment]
Solved
