### ISSUE TITLE
XRF scan/spectrum

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/mxcubeqt#80]
What name we should use for XRF? XRFScan, XRFSpectrum?
Maybe lets use XRFScan as it is in xrfscan branch. This name is used to have similiar syntax with other scans: EnergyScan and AdvancedScan.
Accordingly classes:
- AbstractXRFScan
- XRFScanMockup
- ESRFXRFScan, EMBLXRFScan etc.

**Comment by beteva** [comment]
XRF is not a scan, so we should use XRFSpectra. This in fact has been imposed by the Journal of Applied Crystallography, when in 2009 we have submitted a paper about it.

**Comment by IvarsKarpics** [comment]
Ok I agree. Then lets use XRF spectrum (like the version at the beginning). I will make changes to names in hardware objects and push them in xrfscan branch. 
Hardware object names: AbstractXRFSpectrum, XRFSpectrumMockup, ...
Signals:  xrfSpectrumReady, xrfSpectrumStarted, xrfSpectrumFailed

**Comment by IvarsKarpics** [comment]
XRFSpectrum, xrfSpectrum will be used
