### ISSUE TITLE
Need to select sample to enable Collect button

### ISSUE THREAD

**Issue by ddesanctis** [mxcube/mxcubeqt#83]
In latest release on ID29 it is needed to select the data collection node in the queue to enable collect button, while it should not be necessary. Data collection could be enabled by checking boxes

**Comment by IvarsKarpics** [comment]
Not so clear how it should be. It looks that collect button is not enabled when a new collection is added (it is necessary to click on the tree to trigger refresh). I will fix that. 
Is there any other situation when button is not correctly enabled/disabled?

**Comment by ddesanctis** [comment]
It is not enable with nothing is checked but this is fine IMO

**Comment by IvarsKarpics** [comment]
Solved
