### ISSUE TITLE
lost duplicating functionality

### ISSUE THREAD

**Issue by ddesanctis** [mxcube/mxcubeqt#85]
Ivars, Matias, with the latest update it looks like we lost the duplicating functionality: Selecting a data collection of any kind and clicking add-to-queue was duplicating the data collection (whether it was collected or not). This is a functionality very commonly used in many scenario and it would be nice to have it back soon!

**Comment by IvarsKarpics** [comment]
I also observed this and already made a fix on branch feat_add_collect. I added also feature to add collection to all basket. There are lot of these add to queue features and sometimes by adding new some other is in conflict. I will finish this in a minute and push it into the feat_add_collect branch.

**Comment by IvarsKarpics** [comment]
Should be fixed in feat_add_collect branch. Also I fixed Collect button enable/disable bug when new collection added. Now it is enabled when new collection is added and disabled when delete clicked and no checked elements left.

**Comment by IvarsKarpics** [comment]
Solved

**Comment by ddesanctis** [comment]
Did you commit new changes? Now I got the error, I'm not doing anything
different!

[INFO][2015-03-03 13:45:17] Get current energy
[ERROR][2015-03-03 13:45:23] Uncaught exception : Traceback (most recent
call last):    File
"/users/blissadm/local/mxcube-2/Bricks/widgets/task_toolbox_widget.py",
line 204, in create_task_button_click     self.create_task(task_model,
shape)    File
"/users/blissadm/local/mxcube-2/Bricks/widgets/task_toolbox_widget.py",
line 241, in create_task     new_node =
self.tree_brick.queue_model_hwobj.copy_node(task_node)    File
"/users/blissadm/local/mxcube-2/HardwareObjects/QueueModel.py", line 321,
in copy_node     new_node = node.copy()    File
"/users/blissadm/local/mxcube-2/HardwareObjects/queue_model_objects_v1.py",
line 497, in copy     new_node = copy.deepcopy(self)    File
"/usr/lib/python2.6/copy.py", line 189, in deepcopy     y = _reconstruct(x,
rv, 1, memo)    File "/usr/lib/python2.6/copy.py", line 338, in
_reconstruct     state = deepcopy(state, memo)    File
"/usr/lib/python2.6/copy.py", line 162, in deepcopy     y = copier(x,
memo)    File "/usr/lib/python2.6/copy.py", line 255, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)    File
"/usr/lib/python2.6/copy.py", line 189, in deepcopy     y = _reconstruct(x,
rv, 1, memo)    File "/usr/lib/python2.6/copy.py", line 338, in
_reconstruct     state = deepcopy(state, memo)    File
"/usr/lib/python2.6/copy.py", line 162, in deepcopy     y = copier(x,
memo)    File "/usr/lib/python2.6/copy.py", line 255, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)    File
"/usr/lib/python2.6/copy.py", line 189, in deepcopy     y = _reconstruct(x,
rv, 1, memo)    File "/usr/lib/python2.6/copy.py", line 338, in
_reconstruct     state = deepcopy(state, memo)    File
"/usr/lib/python2.6/copy.py", line 162, in deepcopy     y = copier(x,
memo)    File "/usr/lib/python2.6/copy.py", line 255, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)    File
"/usr/lib/python2.6/copy.py", line 189, in deepcopy     y = _reconstruct(x,
rv, 1, memo)    File "/usr/lib/python2.6/copy.py", line 338, in
_reconstruct     state = deepcopy(state, memo)    File
"/usr/lib/python2.6/copy.py", line 162, in deepcopy     y = copier(x,
memo)    File "/usr/lib/python2.6/copy.py", line 255, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)    File
"/usr/lib/python2.6/copy.py", line 189, in deepcopy     y = _reconstruct(x,
rv, 1, memo)    File "/usr/lib/python2.6/copy.py", line 338, in
_reconstruct     state = deepcopy(state, memo)    File
"/usr/lib/python2.6/copy.py", line 162, in deepcopy     y = copier(x,
memo)    File "/usr/lib/python2.6/copy.py", line 255, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)    File
"/usr/lib/python2.6/copy.py", line 162, in deepcopy     y = copier(x,
memo)    File "/usr/lib/python2.6/copy.py", line 228, in _deepcopy_list
y.append(deepcopy(a, memo))    File "/usr/lib/python2.6/copy.py", line 189,
in deepcopy     y = _reconstruct(x, rv, 1, memo)    File
"/usr/lib/python2.6/copy.py", line 338, in _reconstruct     state =
deepcopy(state, memo)    File "/usr/lib/python2.6/copy.py", line 162, in
deepcopy     y = copier(x, memo)    File "/usr/lib/python2.6/copy.py", line
255, in _deepcopy_dict     y[deepcopy(key, memo)] = deepcopy(value,
memo)    File "/usr/lib/python2.6/copy.py", line 189, in deepcopy     y =
_reconstruct(x, rv, 1, memo)    File "/usr/lib/python2.6/copy.py", line
338, in _reconstruct     state = deepcopy(state, memo)    File
"/usr/lib/python2.6/copy.py", line 162, in deepcopy     y = copier(x,
memo)    File "/usr/lib/python2.6/copy.py", line 255, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)    File
"/usr/lib/python2.6/copy.py", line 189, in deepcopy     y = _reconstruct(x,
rv, 1, memo)    File "/usr/lib/python2.6/copy.py", line 338, in
_reconstruct     state = deepcopy(state, memo)    File
"/usr/lib/python2.6/copy.py", line 162, in deepcopy     y = copier(x,
memo)    File "/usr/lib/python2.6/copy.py", line 255, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)    File
"/usr/lib/python2.6/copy.py", line 162, in deepcopy     y = copier(x,
memo)    File "/usr/lib/python2.6/copy.py", line 292, in _deepcopy_inst
state = deepcopy(state, memo)    File "/usr/lib/python2.6/copy.py", line
162, in deepcopy     y = copier(x, memo)    File
"/usr/lib/python2.6/copy.py", line 255, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)    File
"/usr/lib/python2.6/copy.py", line 162, in deepcopy     y = copier(x,
memo)    File "/usr/lib/python2.6/copy.py", line 292, in _deepcopy_inst
state = deepcopy(state, memo)    File "/usr/lib/python2.6/copy.py", line
162, in deepcopy     y = copier(x, memo)    File
"/usr/lib/python2.6/copy.py", line 255, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)    File
"/usr/lib/python2.6/copy.py", line 189, in deepcopy     y = _reconstruct(x,
rv, 1, memo)    File "/usr/lib/python2.6/copy.py", line 338, in
_reconstruct     state = deepcopy(state, memo)    File
"/usr/lib/python2.6/copy.py", line 162, in deepcopy     y = copier(x,
memo)    File "/usr/lib/python2.6/copy.py", line 255, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)    File
"/usr/lib/python2.6/copy.py", line 181, in deepcopy     rv = reductor(2)
TypeError: cannot serialize 'Hub' object
[INFO][2015-03-03 13:45:25] Get current energy

On Tue, Mar 3, 2015 at 11:04 AM, Ivars Karpics notifications@github.com
wrote:

> Solved
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mxcube/mxcube/issues/85#issuecomment-76917997.

## 

## ἀρετή

Daniele de Sanctis, PhD

Structural Biology Group
ESRF, Grenoble, France
Tel 33 (0)4 76 88 2869
