### ISSUE TITLE
snapshots

### ISSUE THREAD

**Issue by ddesanctis** [mxcube/mxcubeqt#86]
when multiple data collections on different positions are made, snapshots are taken before moving to the new position, while it should first move then take snapshots and collect

**Comment by IvarsKarpics** [comment]
I will have a look at this. I will commit changes to the 2.1. branch.
Should I close previous issues that were solved? About this last python error, a new issue could be created.

**Comment by IvarsKarpics** [comment]
Solved

**Comment by ddesanctis** [comment]
Hi Ivars,

thanks. Yes you can close them except the duplicating one...this afternoon
has been working for 2 hours and not working for other 2 - restart did not
fix the problem, so I do not know what is causing it...quite frustrating I
cannot help much. Error in log is the same

On Tue, Mar 3, 2015 at 11:01 AM, Ivars Karpics notifications@github.com
wrote:

> I will have a look at this. I will commit changes to the 2.1. branch.
> Should I close previous issues that were solved? About this last python
> error, a new issue could be created.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mxcube/mxcube/issues/86#issuecomment-76917571.

## 

## ἀρετή

Daniele de Sanctis, PhD

Structural Biology Group
ESRF, Grenoble, France
Tel 33 (0)4 76 88 2869
