### ISSUE TITLE
XRF and Escan shown as in progress

### ISSUE THREAD

**Issue by ddesanctis** [mxcube/mxcubeqt#88]
XRF and Escan are shown as in progress even when it is done and successful. It is colored in green in queue. Might be spec-related?

**Comment by IvarsKarpics** [comment]
What do you mean? Not so clear how xrf spectrum and energy scan then should proceed?

**Comment by ddesanctis** [comment]
Sorry Ivars, I was not clear, I meant that in queue they are labelled as "in progress" even when they are over and should be labelled "Done"
