### ISSUE TITLE
Remaining time for data collection

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcubeqt#90]
Asked by BM14: display of remaining time for data collection

**Comment by IvarsKarpics** [comment]
Some time ago I made a ProgressBarBrick which displays total and remaining time, and also progress bar. As it is hard to evaluate an overall collection time for all queue (snapshots, moving to centring positions, shutter operations, etc) then this is used for a single queue entry. I which branch should I push it?

**Comment by mguijarr** [comment]
Hi Ivars :)
Nice to hear you already thought about this feature !
I suggest you to create a feature branch, then to merge it to master ; or if it's really small, just push
it to master.
I would need to merge it with 'bm14' branch, I will do it more or less manually since it's far behind
2.1 or master (beamline staff don't want too much frequent updates).

**Comment by IvarsKarpics** [comment]
I will put in 2.1. branch directly, because it is just one brick and two lines in AbstractMulticollect. But I have doubts how to estimate overall collection time. It looks like number_of_frames \* exposure_time is much to less for actual time.

**Comment by ddesanctis** [comment]
This is detector dependent - BM14 for example has a MarCCD that has on top of that the readout time and acceleration and deceleration time for each exposure. 

Better estimation is number_of_frames \* (exposure_time + integration_time)  + number_of_oscillation \* (acceleration_time + deceleration_time)

with integration_time = 0 for pixel detectors. I'm not sure how much is for other detectors, CCD probably 1 second
I'm not sure number_of_oscillation is defined in mxcube though...

**Comment by IvarsKarpics** [comment]
I just pushed new ProgressBarBrick (branch 2.1) which handles this. Also I added exposure time variable to one signal so in the end there is not so much changes in the queue. I guess this will be for each beamline and detector different. I will think how to make it more general and try your suggested equation.
