### ISSUE TITLE
Carry over file name *and* prefix to all data collection methods

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcubeqt#91]
Asked by BM14: when changing prefix in 'Data collection', for example, would be great if prefix could automatically change for 'Characterisation'  or 'Helical' etc.

**Comment by IvarsKarpics** [comment]
We had a similar thoughts, because RAW_DATA gets overcrowded. Suggestion could be to add 
subdirectories: /helical, /characterisation, /energy_scan, /xrf_spectrum, /mesh
Also it could be useful to check selected directory and if it has to much files, then suggest an alternative directory or ask for a subdirectory.

**Comment by ddesanctis** [comment]
I agree on preserving the prefix, if defined manually (i.e. not by ISPyB). I'm not sure for the subdirectory by "collection methods" it adds an extra layer which most of the users don't need/want and can spoil the benefit of using ISPyB

**Comment by IvarsKarpics** [comment]
Ok, creating some extra directories could be messy. But still some directory check could be useful. So the initial idea is then: when prefix is changed in one collection method (for example Data collection) then it should change in others as well (for example in Helical)?

**Comment by ddesanctis** [comment]
Absolutely correct!

On Mon, Mar 30, 2015 at 5:19 PM, Ivars Karpics notifications@github.com
wrote:

> Ok, creating some extra directories could be messy. But still some
> directory check could be useful. So the initial idea is then: when prefix
> is changed in one collection method (for example Data collection) then it
> should change in others as well (for example in Helical)?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mxcube/mxcube/issues/91#issuecomment-87720634.

## 

## ἀρετή

Daniele de Sanctis, PhD

Structural Biology Group
ESRF, Grenoble, France
Tel 33 (0)4 76 88 2869
